import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tyler Louwerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tylerlouwerse-logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          tylerlouwerse.com
        </h1>
      </main>
    </div>
  )
}
